version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: vincent1428
      POSTGRES_DB: go-course
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432" # Expose PostgreSQL on host port 5433, I used 5433 to avoid conflicts with my local PostgreSQL which also runs on 5432
    restart: unless-stopped

volumes:
  postgres_data:
